version = 1

test_patterns = [
  "NearBeach/tests/**",
  "test_*.py"
]

exclude_patterns = [
  "browserstack/**",
  "cypress/**",
  "NearBeach/static/**",
  "Nearbeach/migrations/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"